const CONSTANTS = {
  STORE_FILENAME: 'broker-mailer-store',

  EXCEL_PATH: 'EXCEL_PATH',
  EMAIL_AUTH: 'EMAIL_AUTH',
  EMAIL_FROM: 'EMAIL_FROM',
  TEMPLATE: ' TEMPLATE',

  EV_OPEN_FILE_DIALOG: 'EV_OPEN_FILE_DIALOG',
  EV_PATH_UPDATED: 'EV_PATH_UPDATED',
  EV_EMAIL_AUTH_UPDATED: 'EV_EMAIL_AUTH_UPDATED',
  EV_SEND_EMAILS: 'EV_SEND_EMAILS',
  EV_LOAD_FILE: 'EV_LOAD_FILE',
  EV_RECEIVE_SHEET: 'EV_RECEIVE_SHEET',

  SHEET_NAMES: {
    TRAILERS: 'Trailers',
    DRIVER_EMAILS: 'Broker Emails',
  },

  HEADERS: [
    'UNIT', 'COMMENT', 'HUB_KM', 'LAST_PM_DATE', 'LAST_SAFETY_DATE', 'LAST_B620_DATE',
    'LAST_5YR_DATE', 'DAYS_UNTIL_PM', 'DAYS_UNTIL_SAFETY', 'DAYS_UNTIL_B620',
    'DAYS_UNTIL_5YR', 'DRIVER_NAME',
  ],

  KEYS: {
    UNIT: 'UNIT',
    LAST_PM_DATE: 'LAST_PM_DATE',
    LAST_SAFETY_DATE: 'LAST_SAFETY_DATE',
    LAST_B620_DATE: 'LAST_B620_DATE',
    DAYS_UNTIL_PM: 'DAYS_UNTIL_PM',
    DAYS_UNTIL_SAFETY: 'DAYS_UNTIL_SAFETY',
    DAYS_UNTIL_B620: 'DAYS_UNTIL_B620',
    DRIVER_NAME: 'DRIVER_NAME',
  },

  EMAIL_HEADERS: ['NAME', 'EMAIL'],
  EMAIL_KEYS: {
    NAME: 'NAME',
    EMAIL: 'EMAIL',
  },

  FIRST_DATA_ROW: 3,
  FIRST_EMAIL_ROW: 1,
};

export default CONSTANTS;
