const CONSTANTS = {
  EXCEL_PATH: "EXCEL_PATH",
  EMAIL_AUTH: "EMAIL_AUTH",
  EMAIL_FROM: "EMAIL_FROM",

  EV_OPEN_FILE_DIALOG: "EV_OPEN_FILE_DIALOG",
  EV_PATH_UPDATED: "EV_PATH_UPDATED",
  EV_EMAIL_AUTH_UPDATED: "EV_EMAIL_AUTH_UPDATED",
  EV_SEND_EMAIL: "EV_SEND_EMAIL",
};

export default CONSTANTS;
